version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # Optional: to import .sql file

  redis:
    image: redis:7-alpine

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper

  backend:
    environment:
      - TZ=Europe/Stockholm
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
      - mysql
      - kafka

  frontend:
    # environment:
      # - TZ=Europe/Stockholm
    depends_on:
      - gateway

  car_rental_mailing:
    depends_on:
      - kafka

  gateway:
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - backend
      - redis

volumes:
  mysql_data: