version: '3.8'

services:
  mysql:
    ports:
      - "127.0.0.1:${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # Optional: to import .sql file

  redis:
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"

  backend:
    image: bejoyjose/car_rental_backend:${IMAGE_TAG}
    environment:
      - DB_URL=${MYSQL_URL}
      - DB_USERNAME=${MYSQL_ROOT_USERNAME}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    image: bejoyjose/car_rental_angular:${IMAGE_TAG}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  gateway:
    image: bejoyjose/car_rental_gateway:${IMAGE_TAG}
    environment:
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - GATEWAY_SERVICE_URI=${GATEWAY_SERVICE_URI}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"


