server:
  port: 8082


spring:
  application:
    name: redis-ratelimiter
  redis:
#    host: localhost
    host: host.docker.internal
    port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service
#          uri: http://localhost:8080
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/auth/login
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 2

        - id: user-hello
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/auth/hello
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 60

        - id: user-hello
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/auth/signup
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 2
#Customer APIs
        - id: cars-api
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/cars

        - id: cars-book-api
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/car/book

        - id: get-cars-by-Id-api
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/cars/{carId}

        - id: get-bookings-by-Id-api
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/cars/bookings/{userID}

        - id: search-cars-api
#         uri: http://host.docker.internal:8080
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/search

app:
  cors:
    allowed-origins: "*"
