server:
  port: 8082


spring:
  application:
    name: redis-ratelimiter
  redis:
    host:  ${REDIS_HOST}
    port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/auth/login
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 2

        - id: user-hello
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/auth/hello
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 60

        - id: user-hello
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/auth/signup
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 2
#Customer APIs
        - id: cars-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/cars

        - id: cars-book-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/car/book

        - id: get-cars-by-Id-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/cars/{carId}

        - id: get-bookings-by-Id-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/cars/bookings/{userID}

        - id: search-cars-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/search

        - id: search-cars-s3-upload-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/car/upload

        - id: search-cars-s3-download-api
          uri: ${GATEWAY_SERVICE_URI}
          predicates:
            - Path=/api/customer/car/download/{fileName}

app:
  cors:
    allowed-origins: "*"
