server:
  port: ${NOTIFICATION_PORT}


spring:
  application:
    name: car_rental_mailing

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}   # replace with real email
    password: ${MAIL_PASSWORD}       # replace with app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true