name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push backend image
      run: |
        docker build -t bejoyjose/car_rental_backend ./car_rental_backend
        docker push bejoyjose/car_rental_backend:latest

    - name: Build and push gateway image
      run: |
        docker build -t bejoyjose/car_rental_gateway ./car_rental_gateway
        docker push bejoyjose/car_rental_gateway:latest

    - name: Build and push notification mailing service
      run: |
        docker build -t bejoyjose/notification-service ./notification-service
        docker push bejoyjose/notification-service:latest
        
    - name: Build and push frontend image
      run: |
        docker build \
          --build-arg BASE_API_URL=${{ secrets.BASE_API_URL }} \
          -t bejoyjose/car_rental_angular ./car_rental_angular
        docker push bejoyjose/car_rental_angular:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull bejoyjose/car_rental_backend:latest
          docker pull bejoyjose/car_rental_gateway:latest
          docker pull bejoyjose/car_rental_angular:latest
          cd /home/ec2-user/car-renal-app
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.production pull
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.production down
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.production up -d
          docker image prune -a -f
